name: CI Integration and End to End

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: ['7.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}


    - name: end to end and integration tests
      uses: cypress-io/github-action@v7
      with:
        start: npm run start:test
        wait-on: http://localhost:3030record