name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  call-lint-and-unit-tests:
    uses: ./.github/workflows/lint-unit.yml


  call-integration-tests:
    uses: ./.github/workflows/integration-end-to-end.yml

  push-to-S3:
    needs: [call-lint-and-unit-tests, call-integration-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_key_id: ${{ secrets.AWS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
          aws_region: 'eu-west-2'
        
      - name: Upload to s3
        working-directory: .
        run: aws s3 cp . s3://${{secrets.AWS_BUCKET}}/chris-node-code