name: Linting and Unit tests

on: 
  workflow_call:

jobs:
  linting_unit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26]
        mongodb-version: ['7.0']

    steps:

    - name: Git checkout
      uses: actions/checkout@v6


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'


    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm ci
      name: npm clean installation

    - run: npm run lint
      name: lint tests

    - run: npm run test:unit 
      name: unit tests

  